/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Balances = IDL.Record({
  'ben' : IDL.Float64,
  'tit' : IDL.Float64,
  'myDailys' : IDL.Float64,
  'available' : IDL.Float64,
  'rewards' : IDL.Float64,
});
export const RegistrationError = IDL.Variant({
  'phoneNumberInUse' : IDL.Null,
  'userNotFound' : IDL.Null,
  'balanceOutOfRange' : IDL.Null,
  'incorrectPassword' : IDL.Null,
  'unauthorized' : IDL.Null,
  'userNotRegistered' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'toUserId' : IDL.Text,
  'fromUserId' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerBalances' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : Balances, 'err' : RegistrationError })],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTransactionHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Principal, 'err' : RegistrationError })],
      ['query'],
    ),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : RegistrationError })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transfer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : RegistrationError })],
      [],
    ),
  'updateCallerBalances' : IDL.Func(
      [Balances],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : RegistrationError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Balances = IDL.Record({
    'ben' : IDL.Float64,
    'tit' : IDL.Float64,
    'myDailys' : IDL.Float64,
    'available' : IDL.Float64,
    'rewards' : IDL.Float64,
  });
  const RegistrationError = IDL.Variant({
    'phoneNumberInUse' : IDL.Null,
    'userNotFound' : IDL.Null,
    'balanceOutOfRange' : IDL.Null,
    'incorrectPassword' : IDL.Null,
    'unauthorized' : IDL.Null,
    'userNotRegistered' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'toUserId' : IDL.Text,
    'fromUserId' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerBalances' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : Balances, 'err' : RegistrationError })],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTransactionHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Principal, 'err' : RegistrationError })],
        ['query'],
      ),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : RegistrationError })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transfer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : RegistrationError })],
        [],
      ),
    'updateCallerBalances' : IDL.Func(
        [Balances],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : RegistrationError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };