/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Balances {
  'ben' : number,
  'tit' : number,
  'myDailys' : number,
  'available' : number,
  'rewards' : number,
}
export type RegistrationError = { 'phoneNumberInUse' : null } |
  { 'userNotFound' : null } |
  { 'balanceOutOfRange' : null } |
  { 'incorrectPassword' : null } |
  { 'unauthorized' : null } |
  { 'userNotRegistered' : null };
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'toUserId' : string,
  'fromUserId' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface UserProfile { 'name' : string, 'phoneNumber' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerBalances' : ActorMethod<
    [],
    { 'ok' : Balances } |
      { 'err' : RegistrationError }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTransactionHistory' : ActorMethod<[string], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : Principal } |
      { 'err' : RegistrationError }
  >,
  'register' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : RegistrationError }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transfer' : ActorMethod<
    [string, string, bigint],
    { 'ok' : null } |
      { 'err' : RegistrationError }
  >,
  'updateCallerBalances' : ActorMethod<
    [Balances],
    { 'ok' : null } |
      { 'err' : RegistrationError }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];